variavel = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(variavel))
print("Só tem espaços? ", variavel.isspace())
print("É um número? ", variavel.isnumeric())
print("É alfabético? ", variavel.isalpha())
print("É alfanumérico? ", variavel.isalnum())
print("Está em maiuscúlas? ", variavel.isupper())
print("Está em minuscúlas? ", variavel.islower())
print("Está capitalizada? ", variavel.istitle())